name: htop
version: master
version-script: git -C parts/htop/build/ describe --tags
summary: Interactive processes viewer
description: |
  htop is an ncurses-based process viewer similar to top, but it
  allows one to scroll the list vertically and horizontally to see
  all processes and their full command lines.

  Tasks related to processes (killing, renicing) can be done without
  entering their PIDs.

grade: stable
confinement: strict

apps:
  htop:
    command: bin/htop
    plugs: [system-observe, process-control, mount-observe]

parts:
  htop:
    plugin: autotools
    source: https://github.com/hishamhm/htop
    source-type: git
    source-tag: master
    build-packages: [libncursesw5-dev, pkg-config]
    stage-packages: [lsof]
