name: htop
version: 2.0.1
summary: Interactive processes viewer (WIP)
description:
  Htop is an ncursed-based process viewer similar to top, but it
  allows one to scroll the list vertically and horizontally to see
  all processes and their full command lines.
  .
  Tasks related to processes (killing, renicing) can be done without
  entering their PIDs.

  This is a work in progress. Not fully working due to process isolation.
  Needs to be installed with '--devmode'.

apps:
  htop:
    command: bin/htop

parts:
  htop:
    plugin: autotools
    source: https://github.com/hishamhm/htop
    source-type: git
    source-tag: 2.0.1
    build-packages: [libncurses5-dev, libncursesw5-dev]
