name: htop
version: 2.2.0
version-script: git -C parts/htop/build/ describe --tags
summary: Interactive processes viewer
description: |
  htop is an ncurses-based process viewer similar to top, but it
  allows one to scroll the list vertically and horizontally to see
  all processes and their full command lines. Tasks related to
  processes (killing, renicing) can be done without entering their PIDs.

  Once installed, this snap needs manually connecting to some plugs:
    `sudo snap connect htop:mount-observe`
    `sudo snap connect htop:network-control (optional, for DELAYACCT support)`
    `sudo snap connect htop:process-control`
    `sudo snap connect htop:system-observe`

icon: htop.png

grade: stable
confinement: strict

apps:
  htop:
    command: bin/htop.wrapper
    desktop: share/applications/htop.desktop
    plugs:
      - mount-observe
      - network-control
      - process-control
      - system-observe

parts:
  htop:
    plugin: autotools
    source: https://github.com/hishamhm/htop
    source-type: git
    source-tag: 2.2.0
    configflags:
      - --enable-delayacct
    build-packages:
      - libncursesw5-dev
      - libnl-3-dev
      - libnl-genl-3-dev
      - pkg-config
    stage-packages:
      - libc-bin
      - locales
      - lsof
      - strace
  htop.wrapper:
    plugin: dump
    source: .
    organize:
      htop.wrapper: bin/htop.wrapper

passthrough:
  license: GPL-2.0
