name: htop
base: core18
version: master
version-script: git -C parts/htop/src/ describe --tags
summary: Interactive processes viewer
description: |
  htop is an ncurses-based process viewer similar to top, but it
  allows one to scroll the list vertically and horizontally to see
  all processes and their full command lines. Tasks related to
  processes (killing, renicing) can be done without entering their PIDs.

  Once installed, this snap needs manually connecting to some plugs:
  ```
    sudo snap connect htop:mount-observe
    sudo snap connect htop:network-control  # optional, for DELAYACCT support`
    sudo snap connect htop:process-control
    sudo snap connect htop:system-observe
  ```

icon: htop.png
grade: devel
confinement: strict
license: GPL-2.0

apps:
  htop:
    command: locales-launch htop
    desktop: share/applications/htop.desktop
    plugs:
      - mount-observe
      - network-control
      - process-control
      - system-observe

parts:
  htop:
    plugin: autotools
    source: https://github.com/hishamhm/htop
    source-type: git
    source-branch: master
    configflags:
      - --enable-delayacct
    build-packages:
      - libncursesw5-dev
      - libnl-3-dev
      - libnl-genl-3-dev
      - pkg-config
    stage-packages:
      - libncursesw5
      - libtinfo5
      - lsof
      - strace

  locales-launch:
    source: https://github.com/Lin-Buo-Ren/locales-launch-part.git
    source-subdir: launchers
    plugin: dump
    stage-packages:
    # For localedef(1)
    - libc-bin
    # For locale data used by localedef(1)
    - locales
    # All pre-generated locale data
    # DISABLED: Lots of duplicate data will be included in snap when this is staged, unless the target machine has no resource to generate them in runtime otherwise not using it
    #
    #   Lack of compiled locales breaks gettext based localisation - snapcraft - snapcraft.io
    #   https://forum.snapcraft.io/t/lack-of-compiled-locales-breaks-gettext-based-localisation/3758
    #
    #- locales-all
    organize:
      locales-launch: bin/
